services:
    eu-cuido-dbpg:
        image: postgres:16
        container_name: ${CONTAINER_DBPG}
        ports:
            - '5432:5432'
        volumes:
            - ./data/:/var/lib/postgresql/data_backup
        environment:
            - POSTGRES_DB=${DB_DATABASE}
            - POSTGRES_USER=${DB_USERNAME}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
